services:
  osnocore:
    runtime: sysbox-runc
    volumes:
      - ./home:/home/user

  osnocore-dev:
    runtime: sysbox-runc
    volumes:
      - .:/app
      - ./dev_node_modules:/app/node_modules
      - ./home:/home/user
